# Generated by Django 2.2.7 on 2019-12-07 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sighting',
            old_name='fur_color',
            new_name='primary_fur_color',
        ),
    ]
