# Generated by Django 2.2.7 on 2019-12-08 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0002_auto_20191207_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='age',
            field=models.CharField(choices=[('adult', 'Adult'), ('juvenile', 'Juvenile'), ('', '')], default='adult', help_text='Age', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='date',
            field=models.DateField(help_text='Date'),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='latitude',
            field=models.FloatField(help_text='Latitude'),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='location',
            field=models.CharField(choices=[('ground_plane', 'Ground_Plane'), ('above_ground', 'Above_Ground'), ('', '')], default='ground_plane', help_text='Location', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='longitude',
            field=models.FloatField(help_text='Longitude'),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='primary_fur_color',
            field=models.CharField(choices=[('gray', 'Gray'), ('black', 'Black'), ('cinnamon', 'Cinnamon'), ('', '')], default='gray', help_text='Primary fur color', max_length=10),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='shift',
            field=models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], default='AM', help_text='Shift', max_length=10),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='specific_location',
            field=models.CharField(blank=True, help_text='Specific location', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='squirrel_id',
            field=models.CharField(help_text='Unique Squirrel ID', max_length=32, primary_key=True, serialize=False),
        ),
    ]
